# Dockerfile.express
FROM node:18-bullseye

# Imposta la directory di lavoro nel container
WORKDIR /user/app

COPY package.json ./
RUN npm install

# Esegue l'applicazione con Nodemon per abilitare l'hot reloading
#CMD ["nodemon", "--watch", "/user/app", "dist/app.js"]
CMD ["npm", "run", "start:watch"]
