export const VALIDATION_CONSTANTS = {
    MAX_TOP_UP_AMOUNT: 5000,                
    MIN_DATASET_NAME_LENGTH: 3,
    MAX_DATASET_NAME_LENGTH: 40,
    MIN_TAG_LENGTH: 2,
    MAX_TAG_LENGTH: 20,
    MAX_TAG_NUMBER: 10,
};