export const VALIDATION_PARAMS = {
    MIN_DATASET_NAME_LENGTH: 3,
    MAX_DATASET_NAME_LENGTH: 40,                
    MIN_TOPUP_AMOUNT: 1,
    MAX_TOPUP_AMOUNT: 20000,
    MIN_TAG_LENGTH: 3,
    MAX_TAG_LENGTH: 80,
};